# Generated by Django 2.2.3 on 2019-07-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenoms', models.CharField(max_length=60)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=60)),
                ('ville', models.CharField(max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('numero', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
