# Generated by Django 2.2.3 on 2019-07-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_depot_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='operateur',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='operateur',
            field=models.TextField(max_length=200),
        ),
    ]
