# Generated by Django 2.2.3 on 2019-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20190726_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='depot',
            name='operateur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='operateur',
            field=models.CharField(max_length=20),
        ),
    ]
