# Generated by Django 2.2.3 on 2019-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_auto_20190726_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(default='user', max_length=60),
        ),
    ]
