# Generated by Django 2.2.3 on 2019-07-28 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_utilisateur_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Montant_retrait', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
                ('operateur', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Utilisateur')),
            ],
        ),
    ]
