# Generated by Django 2.2.3 on 2019-07-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_historique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historique',
            old_name='Montant_retrait',
            new_name='Montant',
        ),
    ]
