# Generated by Django 2.2.3 on 2019-07-29 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_auto_20190728_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Championat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cha', models.CharField(max_length=20)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Equipe', models.CharField(max_length=20)),
                ('Championat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Championat')),
            ],
        ),
    ]
