# Generated by Django 2.2.4 on 2019-08-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_auto_20190801_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choixmatch',
            name='matchid',
        ),
    ]
